#!/bin/bash
# Project: MyKeyboard
# This is a config file to store the current KeyBinding.
# System shortcuts
# All in this section should start with super-key.
# WorkSpace about.
# DeskTop about.
# Nautilus about.
# Program Switch.


